[manifest]
version = "1.0.0"
priority = 0

# G.FUNCS.reroll_shop
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = '''
local new_shop_card = create_card_for_shop(G.shop_jokers)
G.shop_jokers:emplace(new_shop_card)'''
position = "at"
payload = '''
local new_shop_card = create_card_for_shop(G.shop_jokers)
G.shop_jokers:emplace(new_shop_card, nil, nil, true, false)'''
match_indent = true
times = 1