[manifest]
version = "1.0.0"
priority = 0

#
# Adds the ability to offer a manual ID for the dissolve SHADERS
# to change the random mask
#

# Sprite:draw_Shader()
[[patches]]
[patches.pattern]
target = "engine/sprite.lua"
pattern = '''G.SHADERS[_shader or 'dissolve']:send("time",123.33412*(_draw_major.ID/1.14212 or 12.5123152)%3000)'''
position = "at"
payload = '''G.SHADERS[_shader or 'dissolve']:send("time",123.33412*(_draw_major.forceID or _draw_major.ID/1.14212 or 12.5123152)%3000)'''
match_indent = true
times = 1

