[manifest]
version = "1.0.0"
priority = 0

#
# Adds an "upgrade hand" context
#

# level_up_hand()
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''update_hand_text({sound = 'button', volume = 0.7, pitch = 0.9, delay = 0}, {level=G.GAME.hands[hand].level})
    delay(1.3)
end'''
position = "at"
payload = '''   update_hand_text({sound = 'button', volume = 0.7, pitch = 0.9, delay = 0}, {level=G.GAME.hands[hand].level})
    delay(1.3)
    SMODS.calculate_context({fnwk_hand_upgraded = true, upgraded = {hand}, amount = amount})
end'''
match_indent = true
times = 1

