[manifest]
version = "1.0.0"
priority = 0

# localize
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''localize{type = 'other', key = 'playing_card', set = 'Other', nodes = full_UI_table.name, vars = {localize(specific_vars.value, 'ranks'), localize(specific_vars.suit, 'suits_plural'), colours = {specific_vars.colour}}}'''
position = "at"
payload = '''localize{type = 'other', key = 'playing_card', set = 'Other', nodes = full_UI_table.name, vars = {localize(specific_vars.value, 'ranks'), localize(specific_vars.suit, 'suits_plural'), colours = {specific_vars.colour}, suit_key = specific_vars.suit}}'''
match_indent = true
times = 1