[manifest]
version = "1.0.0"
priority = 0

#
# Adds a "pre_draw" context
#

# new_round()
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''G.GAME.current_round.discards_used = 0
G.GAME.current_round.reroll_cost_increase = 0
G.GAME.current_round.used_packs = {}'''
position = "after"
payload = '''G.GAME.current_round.packs_rerolled = 0'''
match_indent = true
times = 1


